application: squednetwork
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.png
  static_files: favicon.png
  upload: favicon\.png

- url: /static
  static_dir: static
- url: .*
  script: main.app
  login: optional


libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "latest"
